import {
  Activity,
  ArrowDown,
  ArrowRight,
  BarChart3,
  Bell,
  Blocks,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Database,
  Download,
  Factory,
  FileText,
  Globe,
  IndianRupee,
  Leaf,
  Lightbulb,
  Link2,
  Mail,
  MapPin,
  MessageSquare,
  Monitor,
  Network,
  Phone,
  PieChart,
  Play,
  Plug,
  Radio,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  TrendingDown,
  TrendingUp,
  Waves,
  Wifi,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, any> = {
  activity: Activity,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'bar-chart-3': BarChart3,
  bell: Bell,
  blocks: Blocks,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  cloud: Cloud,
  database: Database,
  download: Download,
  factory: Factory,
  'file-text': FileText,
  globe: Globe,
  'indian-rupee': IndianRupee,
  leaf: Leaf,
  'lightbulb': Lightbulb,
  'link-2': Link2,
  mail: Mail,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  monitor: Monitor,
  network: Network,
  phone: Phone,
  'pie-chart': PieChart,
  play: Play,
  plug: Plug,
  radio: Radio,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  waves: Waves,
  wifi: Wifi,
  zap: Zap,
}

export function SiteIcon({ token, className }: { token: string; className?: string }) {
  const Icon = ICON_MAP[token] ?? Activity
  return <Icon className={className} aria-hidden="true" />
}
