import {
  Activity,
  ArrowDown,
  ArrowRight,
  BarChart3,
  Bell,
  Blocks,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Cpu,
  Database,
  Download,
  Factory,
  FileText,
  Globe,
  IndianRupee,
  Leaf,
  Lightbulb,
  Link2,
  Mail,
  MapPin,
  MessageSquare,
  Monitor,
  Network,
  Phone,
  PieChart,
  Play,
  Plug,
  Radio,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  TrendingDown,
  TrendingUp,
  Waves,
  Wifi,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, any> = {
  '⚡': Zap,
  '📡': Radio,
  '☁️': Cloud,
  '🎚️': SlidersHorizontal,
  '🌿': Leaf,
  '🖥️': Monitor,
  '📊': BarChart3,
  '🛡️': ShieldCheck,
  '🔌': Plug,
  '⚙️': Settings,
  '🔔': Bell,
  '📄': FileText,
  '🔒': ShieldCheck,
  '📱': Smartphone,
  '⏱️': Activity,
  '✉️': Mail,
  '🔍': Search,
  '🥧': PieChart,
  '💰': IndianRupee,
  '🔗': Link2,
  '🏭': Factory,
  '🌊': Waves,
  '💡': Lightbulb,
  '🗄️': Database,
  '💬': MessageSquare,
  '💾': Database,
  '🌍': Globe,
  '🧩': Blocks,
  '✅': CheckCircle2,
  '📉': TrendingDown,
  '📈': TrendingUp,
  '📶': Wifi,
  '🔆': Activity,
  '🌐': Network,
  '📻': Radio,
  '▶': Play,
  '⬇': Download,
  '✓': Check,
  '✦': Check,
  '☎': Phone,
  '📞': Phone,
  '📍': MapPin,
  '→': ArrowRight,
  '↓': ArrowDown,
  '‹': ChevronLeft,
  '›': ChevronRight,
  'rocket': Activity,
  'play': Play,
  'download': Download,
  'phone': Phone,
  'mail': Mail,
  'map-pin': MapPin,
  'globe': Globe,
  'check': Check,
  'arrow-right': ArrowRight,
  'arrow-down': ArrowDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'zap': Zap,
}

export function SiteIcon({ token, className }: { token: string; className?: string }) {
  const Icon = ICON_MAP[token] ?? Activity
  return <Icon className={className} aria-hidden="true" />
}
